variables:
    OWNER: tuwrobotics
    PREFIX: tuw

stages:
    - build

run_tests:
    tags:
    - runner-ralf
    stage: build
    image: $OWNER/$PREFIX-jazzy-desktop

    before_script:
        - mkdir ~/.ssh/
        - cp $SSH_KEY_PRIV ~/.ssh/id_ed25519
        - cp $SSH_KEY_PUB ~/.ssh/id_ed25519.pub
        - chmod 700 ~/.ssh/id_ed25519
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - make clone
    script:
        - export ROS_DISTRO=jazzy
        - make build