FROM ros:jazzy
ARG ROS_DISTRO=jazzy

# update pkg index
RUN apt-get update && apt-get upgrade -y

# install utils (like git, vim, nano, ...)
RUN apt-get install -y  \
       gdb              \
       bash-completion  \
       cmake-curses-gui \
       rsync            \
       nano             \
       vim              \
       wget             \
       tmux             \
       tmuxinator       \
       iputils-ping     \
       keychain         

# dependencies for stage and stage_ros2
RUN apt-get install -y git  g++ libjpeg8-dev libpng-dev libglu1-mesa-dev libltdl-dev libfltk1.3-dev

# dependencies for geographiclib
RUN apt-get install -y geographiclib-tools libgeographiclib-dev

 #  GUI tools
RUN apt-get install  -y \
      geany \
      meld 
      
# install some ros pgks
RUN apt-get install  -y \
      ros-$ROS_DISTRO-rviz2 \
      ros-$ROS_DISTRO-ament-cmake-cppcheck \
      ros-$ROS_DISTRO-ament-cmake-cpplint \
      ros-$ROS_DISTRO-ament-cmake-lint-cmake \ 
      ros-$ROS_DISTRO-ament-cmake-test \
      ros-$ROS_DISTRO-ament-cmake-uncrustify \ 
      ros-$ROS_DISTRO-ament-cmake-vendor-package \ 
      ros-$ROS_DISTRO-ament-cmake-xmllint \
      ros-$ROS_DISTRO-ament-cppcheck \
      ros-$ROS_DISTRO-ament-cpplint \ 
      ros-$ROS_DISTRO-geographic-msgs \
      ros-$ROS_DISTRO-laser-filters \
      ros-$ROS_DISTRO-navigation2 \
      ros-$ROS_DISTRO-rmw-cyclonedds-cpp \
      ros-$ROS_DISTRO-slam-toolbox \
      ros-$ROS_DISTRO-teleop-tools \
      ros-$ROS_DISTRO-teleop-tools \
      ros-$ROS_DISTRO-teleop-twist-joy \
      ros-$ROS_DISTRO-tf-transformations \
      ros-$ROS_DISTRO-tf2-tools \
      ros-$ROS_DISTRO-xacro \
      ros-$ROS_DISTRO-rqt-gui \
      ros-$ROS_DISTRO-rqt-common-plugins \
      ros-$ROS_DISTRO-rqt-tf-tree

# install python pip
RUN apt-get install -y \
      python3-pip \
      python3-colcon-common-extensions
